HewlettPackard/oneview-redfish-toolkit

tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/12)
=> Remove py27 from tox file

tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/13)
=> Change docs generate in tox file to use python3.5

.travis.yml, tox.ini
Closes #14 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/19)
=> Add .travis.yml file

requirements.txt, test-requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/26)
=> Remove unnecessary dependencies generated by cookiecutter

run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/27)
=> Remove unnecessary dependencies 

requirements.txt
Fixes #16 
Fixes #17 
Fixes #18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/31)
=> Fix requirements.txt by removing collections

doc/source/oneview_redfish_toolkit.blueprints.rst, oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system_collection.py, oneview_redfish_toolkit/mockups/ComputerSystem.json, oneview_redfish_toolkit/mockups/ServerHardware.json, oneview_redfish_toolkit/mockups/ServerHardwareTypes.json, oneview_redfish_toolkit/redfish.ini, oneview_redfish_toolkit/tests/api/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py
Closes #21, closes #22, closes #23, closes #24, closes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/46)
=> Add ComputerSystem

oneview_redfish_toolkit/api/service_root.py, oneview_redfish_toolkit/blueprints/service_root.py, oneview_redfish_toolkit/mockups/ServiceRoot.json, oneview_redfish_toolkit/tests/api/test_service_root.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py
Closes #42
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/48)
=> Add OneView UUID to ServiceRoot

oneview_redfish_toolkit/blueprints/chassis.py
Closes #43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/51)
=> Implement chassis router

oneview_redfish_toolkit/api/chassis.py, oneview_redfish_toolkit/api/computer_system.py
Closes #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/69)
=> Fix return value of _map_indicator_led function

oneview_redfish_toolkit/api/blade_manager.py, oneview_redfish_toolkit/api/enclosure_manager.py, oneview_redfish_toolkit/api/manager.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/mockups/BladeManager.json, oneview_redfish_toolkit/mockups/EnclosureManager.json, oneview_redfish_toolkit/tests/api/test_blade_manager.py, oneview_redfish_toolkit/tests/api/test_enclosure_manager.py, oneview_redfish_toolkit/tests/blueprints/test_manager.py
Closes #54 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/84)
=> Add managers to blade and enclosure

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/mockups/ComputerSystem.json, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
Closes #56.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/85)
=> Show PowerOps for ComputerSystem

oneview_redfish_toolkit/api/blade_manager.py, oneview_redfish_toolkit/mockups_redfish/BladeManager.json
change blade_manager to report the ilo firmware version instead of the OV firmware version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/89)
=> report BMC firmware in blade_manager

oneview_redfish_toolkit/api/blade_manager.py, oneview_redfish_toolkit/api/manager.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/mockups_redfish/BladeManager.json, oneview_redfish_toolkit/tests/api/test_blade_manager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/92)
=> Blade manager firmware version

oneview_redfish_toolkit/api/blade_chassis.py, oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/enclosure_chassis.py, oneview_redfish_toolkit/mockups_redfish/BladeChassis.json, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json, oneview_redfish_toolkit/mockups_redfish/EnclosureChassis.json
closes #86
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/94)
=> Add Managers Links to ComputerSystem, EnclosureChassis and BladeChassis

oneview_redfish_toolkit/api/blade_manager.py, oneview_redfish_toolkit/api/enclosure_manager.py, oneview_redfish_toolkit/mockups_redfish/BladeManager.json, oneview_redfish_toolkit/mockups_redfish/EnclosureManager.json
add description to blade manager ("HPE Integrated Lights Out") and to enclosure manager ( "HPE Onboard Administrator")
modify tests to pass
=> add description to manager components

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/storage_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/storage_collection.py, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json, oneview_redfish_toolkit/mockups_redfish/StorageCollection.json, oneview_redfish_toolkit/schemas/StorageCollection.json, oneview_redfish_toolkit/tests/api/test_storage_collection.py, oneview_redfish_toolkit/tests/blueprints/test_storage_collection.py, redfish.conf
Add StorageCollection on ComputerSystem.
Closes #97 and closes #99
=> Implement StorageCollection and add StorageCollection On ComputerSystem

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/thermal.py, oneview_redfish_toolkit/mockups_redfish/BladeChassisThermal.json, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json, oneview_redfish_toolkit/mockups_redfish/EnclosureChassisThermal.json, oneview_redfish_toolkit/mockups_redfish/RackChassisThermal.json
=> Fix odata missing info on Thermal and Systems

oneview_redfish_toolkit/api/chassis.py, oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/manager.py, oneview_redfish_toolkit/api/status_mapping.py, oneview_redfish_toolkit/tests/api/test_status_mapping.py
=> Fix status for System, Chassis and Manager

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/chassis.py, oneview_redfish_toolkit/blueprints/chassis_collection.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system_collection.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/blueprints/manager_collection.py, oneview_redfish_toolkit/mockups_errors/EnclosuresNotFound.json, oneview_redfish_toolkit/mockups_errors/Error500.json, oneview_redfish_toolkit/mockups_errors/InvalidJsonKey.json, oneview_redfish_toolkit/mockups_errors/RacksNotFound.json, oneview_redfish_toolkit/mockups_errors/ServerHardwareListNotFound.json, oneview_redfish_toolkit/tests/blueprints/test_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py, oneview_redfish_toolkit/tests/blueprints/test_manager.py, oneview_redfish_toolkit/tests/blueprints/test_manager_collection.py, oneview_redfish_toolkit/tests/blueprints/test_odata.py, oneview_redfish_toolkit/tests/blueprints/test_storage_collection.py, oneview_redfish_toolkit/tests/blueprints/test_thermal.py
closes #75 
closes #76 
closes #77 
closes #78 
closes #79 
closes #80 
closes #110
=> One PR to close them all

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json
=> Fix link to Reset on ComputerSystem

oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/service_root.py, oneview_redfish_toolkit/blueprints/storage_collection.py, oneview_redfish_toolkit/blueprints/thermal.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py
=> Fix error messages

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json
=> Add EthernetInterfaces link to ComputerSystem

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/network_interface_collection.py, oneview_redfish_toolkit/api/redfish_json_validator.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_interface_collection.py, oneview_redfish_toolkit/mockups_redfish/ComputerSystem.json, oneview_redfish_toolkit/mockups_redfish/NetworkInterfaceCollection.json, oneview_redfish_toolkit/schemas/NetworkInterfaceCollection.json, oneview_redfish_toolkit/tests/api/test_network_interface_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_interface_collection.py, redfish.conf
=> Add network interface collection#119

oneview_redfish_toolkit/api/network_interface.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_interface.py, oneview_redfish_toolkit/blueprints/network_interface_collection.py, oneview_redfish_toolkit/mockups_redfish/NetworkInterface3.json, oneview_redfish_toolkit/schemas/NetworkInterface.v1_1_0.json, oneview_redfish_toolkit/tests/api/test_network_interface.py, oneview_redfish_toolkit/tests/blueprints/test_network_interface.py, redfish.conf
=> Add NetworkInterface

oneview_redfish_toolkit/api/network_device_function_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_device_function_collection.py, oneview_redfish_toolkit/mockups_redfish/NetworkDeviceFunctionCollection.json, oneview_redfish_toolkit/schemas/NetworkDeviceFunctionCollection.json, oneview_redfish_toolkit/tests/api/test_network_device_function_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_device_function_collection.py, redfish.conf
=> Add device function collection#125

redfish.conf
=> Disable HTTPS by default

oneview_redfish_toolkit/api/storage.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/storage.py, oneview_redfish_toolkit/mockups_redfish/Storage.json, oneview_redfish_toolkit/schemas/Storage.v1_2_0.json, oneview_redfish_toolkit/tests/api/test_storage.py, oneview_redfish_toolkit/tests/blueprints/test_storage.py, redfish.conf
=> Implement Storage

oneview_redfish_toolkit/api/network_port_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_port_collection.py, oneview_redfish_toolkit/mockups_redfish/NetworkPortCollection.json, oneview_redfish_toolkit/schemas/NetworkPortCollection.json, oneview_redfish_toolkit/tests/api/test_network_port_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_port_collection.py, redfish.conf
=> Implement NetworkPortCollection

oneview_redfish_toolkit/api/blade_chassis.py, oneview_redfish_toolkit/mockups_redfish/BladeChassis.json
=> Add NetworkAdapters odata.id to BladeChassis

oneview_redfish_toolkit/blueprints/network_interface.py
=> Fix device_id range validation

oneview_redfish_toolkit/api/network_adapter_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_adapter_collection.py, oneview_redfish_toolkit/mockups_redfish/NetworkAdapterCollection.json, oneview_redfish_toolkit/schemas/NetworkAdapterCollection.json, oneview_redfish_toolkit/tests/api/test_network_adapter_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_adapter_collection.py, redfish.conf
=> Add network adapter collection

oneview_redfish_toolkit/api/network_adapter.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_adapter.py, oneview_redfish_toolkit/mockups_redfish/NetworkAdapters3.json, oneview_redfish_toolkit/schemas/NetworkAdapter.v1_0_1.json, oneview_redfish_toolkit/tests/api/test_network_adapter.py, oneview_redfish_toolkit/tests/blueprints/test_network_adapter.py, redfish.conf
=> Add NetworkAdapter

oneview_redfish_toolkit/api/network_interface.py, oneview_redfish_toolkit/mockups_redfish/NetworkInterface3.json
=> Fix NetworkInterfaceLinks

oneview_redfish_toolkit/api/network_device_function.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/network_device_function.py, oneview_redfish_toolkit/mockups_redfish/NetworkDeviceFunction1_1_a.json, oneview_redfish_toolkit/schemas/NetworkDeviceFunction.v1_1_0.json, oneview_redfish_toolkit/tests/api/test_network_device_function.py, oneview_redfish_toolkit/tests/blueprints/test_network_device_function.py, redfish.conf
=> Add NetworkDeviceFunction

oneview_redfish_toolkit/blueprints/odata.py
=> Removing error handler from odata blueprint

oneview_redfish_toolkit/api/metadata.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/metadata.py, oneview_redfish_toolkit/mockups_redfish/Metadata.json, oneview_redfish_toolkit/tests/api/test_metadata.py, oneview_redfish_toolkit/tests/blueprints/test_metadata.py, redfish.conf
=> Add metadata#145

oneview_redfish_toolkit/api/network_adapter.py, oneview_redfish_toolkit/mockups_redfish/NetworkAdapters3.json
=> Fix NetworkDeviceFunctionCount

oneview_redfish_toolkit/api/storage.py
=> Fix storage build

oneview_redfish_toolkit/app.py
=> Set OData-Version header for all responses

oneview_redfish_toolkit/app.py, tox.ini
=> Fix tox starting the app

run.cmd
=> Add windows start script, run.cmd

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/chassis.py, oneview_redfish_toolkit/blueprints/chassis_collection.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system_collection.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/blueprints/manager_collection.py, oneview_redfish_toolkit/blueprints/metadata.py, oneview_redfish_toolkit/blueprints/network_adapter.py, oneview_redfish_toolkit/blueprints/network_adapter_collection.py, oneview_redfish_toolkit/blueprints/network_device_function.py, oneview_redfish_toolkit/blueprints/network_device_function_collection.py, oneview_redfish_toolkit/blueprints/network_interface.py, oneview_redfish_toolkit/blueprints/network_interface_collection.py, oneview_redfish_toolkit/blueprints/network_port.py, oneview_redfish_toolkit/blueprints/network_port_collection.py, oneview_redfish_toolkit/blueprints/odata.py, oneview_redfish_toolkit/blueprints/service_root.py, oneview_redfish_toolkit/blueprints/storage.py, oneview_redfish_toolkit/blueprints/storage_collection.py, oneview_redfish_toolkit/blueprints/thermal.py, oneview_redfish_toolkit/util.py
=> Change logging.error to logging.excetion

README.md, oneview_redfish_toolkit/api/blade_manager.py, oneview_redfish_toolkit/api/enclosure_chassis.py, oneview_redfish_toolkit/api/metadata.py, oneview_redfish_toolkit/api/network_adapter.py, oneview_redfish_toolkit/api/network_device_function.py, oneview_redfish_toolkit/api/odata.py, oneview_redfish_toolkit/api/redfish_error.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/chassis_collection.py, oneview_redfish_toolkit/blueprints/manager_collection.py, oneview_redfish_toolkit/blueprints/network_device_function.py, oneview_redfish_toolkit/blueprints/service_root.py, oneview_redfish_toolkit/tests/blueprints/test_thermal.py, oneview_redfish_toolkit/util.py
- Fix documentation.
- Fix typos.
- Fix variable names to follow PEP8 recommendations.
- Fix the order of catching exceptions.
=> Some fixes related to docs and PEP8

oneview_redfish_toolkit/api/network_adapter.py, oneview_redfish_toolkit/api/network_device_function.py, oneview_redfish_toolkit/api/network_device_function_collection.py, oneview_redfish_toolkit/api/network_interface.py, oneview_redfish_toolkit/api/network_port.py, oneview_redfish_toolkit/api/network_port_collection.py, oneview_redfish_toolkit/api/redfish_json_validator.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/tests/api/test_network_port.py, oneview_redfish_toolkit/tests/api/test_redfish_json_validator.py
Closes #187 and #171.
- Tests created.
- Fixed all retrieval of devices in network objects.
=> Retrieve device based on deviceNumber

oneview_redfish_toolkit/api/metadata.py, oneview_redfish_toolkit/mockups/redfish/Metadata.xml, oneview_redfish_toolkit/tests/api/test_metadata.py, oneview_redfish_toolkit/tests/blueprints/test_metadata.py
=> Fix wrong links in XML metadata

README.md, oneview_redfish_toolkit/app.py, redfish.conf
Closes #198.
- Added host IP field in redfish.conf
- Updated the host in app.py for the host in redfish.conf
- Added host information in the README file
=> Specify host IP address to launch the service

oneview_redfish_toolkit/api/subscription_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/subscription_collection.py, oneview_redfish_toolkit/mockups/redfish/SubscriptionCollection.json, oneview_redfish_toolkit/tests/api/test_subscription_collection.py, oneview_redfish_toolkit/tests/blueprints/test_subscription_collection.py, oneview_redfish_toolkit/util.py, redfish.conf
=> Implement GET SubscriptionCollection

oneview_redfish_toolkit/api/subscription.py, oneview_redfish_toolkit/api/subscription_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/subscription.py, oneview_redfish_toolkit/mockups/redfish/Subscription.json, oneview_redfish_toolkit/tests/api/test_subscription.py, oneview_redfish_toolkit/tests/blueprints/test_subscription.py, oneview_redfish_toolkit/util.py, requirements.txt
=> Implement POST Subscription

oneview_redfish_toolkit/tests/blueprints/test_event_service.py, oneview_redfish_toolkit/tests/test_util.py
Create test to `load_event_service_info()` in `util.py` and improve the `event_service` test (mocking the global variables). Also checks if `event_service` section exists in the CONFIG file.
=> Improve some unit tests

oneview_redfish_toolkit/api/subscription.py, oneview_redfish_toolkit/api/subscription_collection.py, oneview_redfish_toolkit/blueprints/subscription.py, oneview_redfish_toolkit/mockups/redfish/Subscription.json, oneview_redfish_toolkit/tests/blueprints/test_subscription.py
=> Implement GET Subscription

README.md, oneview_redfish_toolkit/api/scmb.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/tests/api/test_scmb.py, requirements.txt
=> add scmb connection

oneview_redfish_toolkit/api/network_interface_collection.py, oneview_redfish_toolkit/mockups/redfish/NetworkInterfaceCollection.json
=> Fix NetworkInterface URL in NetworkInterfaceCollection

oneview_redfish_toolkit/api/subscription.py, oneview_redfish_toolkit/api/subscription_collection.py, oneview_redfish_toolkit/blueprints/subscription.py, oneview_redfish_toolkit/tests/blueprints/test_subscription.py
=> Implements DELETE Subscription

CHANGELOG.md, oneview_redfish_toolkit/api/event.py, oneview_redfish_toolkit/api/event_service.py, oneview_redfish_toolkit/api/scmb.py, oneview_redfish_toolkit/api/service_root.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/event_service.py, oneview_redfish_toolkit/event_dispatcher.py, oneview_redfish_toolkit/mockups/redfish/Alert.json, oneview_redfish_toolkit/mockups/redfish/EventDestination.json, oneview_redfish_toolkit/mockups/redfish/EventService.json, oneview_redfish_toolkit/mockups/redfish/ServiceRoot.json, oneview_redfish_toolkit/tests/api/test_event.py, oneview_redfish_toolkit/tests/api/test_event_service.py, oneview_redfish_toolkit/tests/api/test_scmb.py, oneview_redfish_toolkit/tests/api/test_service_root.py, oneview_redfish_toolkit/tests/blueprints/test_event_service.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py, oneview_redfish_toolkit/tests/test_event_dispatcher.py, oneview_redfish_toolkit/tests/test_util.py, oneview_redfish_toolkit/util.py
=> Add support for Redfish EventService API

CHANGELOG.md, oneview_redfish_toolkit/api/resource_block_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/resource_block_collection.py, oneview_redfish_toolkit/mockups/redfish/ResourceBlockCollection.json, oneview_redfish_toolkit/tests/api/test_resource_block_collection.py, oneview_redfish_toolkit/tests/blueprints/test_composition_service.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block_collection.py
* Implement the ResourceBlocks API (collection)
* Load OneView server hardware resources and create the corresponding resource block for each of them
Closes #233
=> Add ResourceBlockCollection resource

CHANGELOG.md, oneview_redfish_toolkit/api/scmb.py, oneview_redfish_toolkit/tests/api/test_scmb.py, oneview_redfish_toolkit/tests/base_test.py, oneview_redfish_toolkit/tests/test_event_dispatcher.py, oneview_redfish_toolkit/tests/test_util.py, oneview_redfish_toolkit/util.py
=> Check OneView availability

scripts/oneview-redfish-toolkit, setup.cfg, setup.py
Updating installation package requirements and details.
=> Updating installation package

oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, oneview_redfish_toolkit/tests/blueprints/test_composition_service.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py, oneview_redfish_toolkit/tests/blueprints/test_event_service.py, oneview_redfish_toolkit/tests/blueprints/test_manager.py, oneview_redfish_toolkit/tests/blueprints/test_manager_collection.py, oneview_redfish_toolkit/tests/blueprints/test_metadata.py, oneview_redfish_toolkit/tests/blueprints/test_network_adapter.py, oneview_redfish_toolkit/tests/blueprints/test_network_adapter_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_device_function.py, oneview_redfish_toolkit/tests/blueprints/test_network_device_function_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_interface.py, oneview_redfish_toolkit/tests/blueprints/test_network_interface_collection.py, oneview_redfish_toolkit/tests/blueprints/test_network_port.py, oneview_redfish_toolkit/tests/blueprints/test_network_port_collection.py, oneview_redfish_toolkit/tests/blueprints/test_odata.py, oneview_redfish_toolkit/tests/blueprints/test_redfish_base.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block_collection.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py, oneview_redfish_toolkit/tests/blueprints/test_session.py, oneview_redfish_toolkit/tests/blueprints/test_storage.py, oneview_redfish_toolkit/tests/blueprints/test_storage_collection.py, oneview_redfish_toolkit/tests/blueprints/test_subscription.py, oneview_redfish_toolkit/tests/blueprints/test_subscription_collection.py, oneview_redfish_toolkit/tests/blueprints/test_thermal.py, oneview_redfish_toolkit/tests/blueprints/test_zone_collection.py
Add a BaseFlaskTest class that encapsulates the error handling
Closes #276
=> Remove duplicated code in blueprint tests

oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
=> Implement Delete for  Composed Resource

test-requirements.txt, tox.ini
Remove reference for OpenStack constraints file in pip install
=> Fix oslotest module version

oneview_redfish_toolkit/api/zone.py, oneview_redfish_toolkit/mockups/redfish/Zone.json, oneview_redfish_toolkit/mockups/redfish/ZoneWithoutNetwork.json, oneview_redfish_toolkit/tests/api/test_zone.py
=> Include Network resource blocks in a Resource Zone

CHANGELOG.md, oneview_redfish_toolkit/api/zone.py, oneview_redfish_toolkit/mockups/redfish/Zone.json, oneview_redfish_toolkit/mockups/redfish/ZoneWithoutDrives.json, oneview_redfish_toolkit/mockups/redfish/ZoneWithoutNetwork.json
Closes https://github.com/HewlettPackard/oneview-redfish-toolkit/issues/311
=> Updating CapabilitiesObject on Resource Zone

CHANGELOG.md, oneview_redfish_toolkit/api/computer_system_collection.py
Closes https://github.com/HewlettPackard/oneview-redfish-toolkit/issues/329
=> Fixing System Collection count issue

CHANGELOG.md, oneview_redfish_toolkit/api/computer_system_collection.py, oneview_redfish_toolkit/blueprints/computer_system_collection.py, oneview_redfish_toolkit/mockups/redfish/ComputerSystemCollection.json, oneview_redfish_toolkit/mockups/redfish/ServerProfilesAppliedCollectionEmpty.json, oneview_redfish_toolkit/tests/api/test_computer_system_collection.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py
=> Implement "@Redfish.CollectionCapabilities" in the Systems collection

oneview_redfish_toolkit/api/metadata.py, oneview_redfish_toolkit/api/redfish_error.py, oneview_redfish_toolkit/api/redfish_json_validator.py, oneview_redfish_toolkit/api/scmb.py, oneview_redfish_toolkit/api/service_root.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/event_service.py, oneview_redfish_toolkit/blueprints/session.py, oneview_redfish_toolkit/blueprints/subscription.py, oneview_redfish_toolkit/blueprints/subscription_collection.py, oneview_redfish_toolkit/conf/redfish.conf, oneview_redfish_toolkit/config.py, oneview_redfish_toolkit/connection.py, oneview_redfish_toolkit/tests/api/test_service_root.py, oneview_redfish_toolkit/tests/base_test.py, oneview_redfish_toolkit/tests/blueprints/test_event_service.py, oneview_redfish_toolkit/tests/blueprints/test_metadata.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py, oneview_redfish_toolkit/tests/blueprints/test_subscription_collection.py, oneview_redfish_toolkit/tests/test_config.py, oneview_redfish_toolkit/tests/test_connection.py, oneview_redfish_toolkit/tests/test_util.py, oneview_redfish_toolkit/util.py
Closes #266 
Refatoring util into:
- config.py
- connection.py
- util.py
Now each file is responsible to access its own global vars.
=> Redfish config file should have a list of OneView IPs

oneview_redfish_toolkit/api/storage_resource_block.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
=> Fixes Storage Resource Block to show Composed/unused status properly

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/authentication.py, oneview_redfish_toolkit/blueprints/session.py, oneview_redfish_toolkit/tests/blueprints/test_session.py, oneview_redfish_toolkit/tests/test_authentication.py
=> Authentication for each request should be based on the REDFISH_SESSION_TOKEN defined during Redfish session creation

oneview_redfish_toolkit/api/capabilities_object.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/zone.py, oneview_redfish_toolkit/mockups/redfish/CapabilitiesObjectWithSPTIdAndEnclId.json, oneview_redfish_toolkit/tests/api/test_capabilities_object.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
- The new ID could be only the SPT Id ou SPT Id + Enclosure Id
Closes #368
=> Updates GET capabilities object for handle the new ID

oneview_redfish_toolkit/api/storage.py, oneview_redfish_toolkit/tests/blueprints/test_storage.py
=> Fixing Storage for a Composed System when there are no drives

oneview_redfish_toolkit/api/chassis.py, oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/manager.py, oneview_redfish_toolkit/api/processor.py, oneview_redfish_toolkit/api/resource_block_computer_system.py, oneview_redfish_toolkit/api/server_hardware_resource_block.py, oneview_redfish_toolkit/api/status_mapping.py, oneview_redfish_toolkit/api/storage.py, oneview_redfish_toolkit/mockups/redfish/BladeManager.json, oneview_redfish_toolkit/mockups/redfish/EnclosureManager.json, oneview_redfish_toolkit/mockups/redfish/RackChassis.json, oneview_redfish_toolkit/mockups/redfish/ServerHardwareResourceBlock.json, oneview_redfish_toolkit/tests/api/test_status_mapping.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
- Adding Status struct for Computer System Resource Block and Composed System
- Refactoring Status Mapping to be reused
- Adding status unit tests for resource block and computer system files
- Updating redfish server hardware mockup with status property
Closes #296
=> Update Status for Computer System Resource Block and for Composed System based on Oneview response

oneview_redfish_toolkit/strategy_multiple_oneview.py
=> Fixing multiple OneViews support for get by reflection before persist

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/storage.py, oneview_redfish_toolkit/handler_multiple_oneview.py, oneview_redfish_toolkit/services/computer_system_service.py, oneview_redfish_toolkit/strategy_multiple_oneview.py, oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
- Uses task for monitoring server profile until the uuid is available.
Closes #375
=> Changes POST to compose a system to return the new uuid as soon as profile uuid is available

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/config.py, oneview_redfish_toolkit/connection.py, oneview_redfish_toolkit/multiple_oneview.py, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/test_multiple_oneview.py
Check the issue #414 for more details. 😉 
Closes #414
=> Fixes the problem due to conf mode be requiring auth token

oneview_redfish_toolkit/authentication.py, oneview_redfish_toolkit/multiple_oneview.py
=> Handling Concurrency for cached data

oneview_redfish_toolkit/api/errors.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/authentication.py, oneview_redfish_toolkit/blueprints/util/response_builder.py, oneview_redfish_toolkit/conf/redfish.conf, oneview_redfish_toolkit/mockups/redfish/SessionForLoginWithDomain.json, oneview_redfish_toolkit/tests/blueprints/test_session.py, oneview_redfish_toolkit/tests/test_authentication.py
- Supports auth authLoginDomain using both conf and session mode.
Closes #421
=> Adds support for authLoginDomain

oneview_redfish_toolkit/api/capabilities_object.py, oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/mockups/oneview/ServerProfile.json, oneview_redfish_toolkit/mockups/oneview/ServerProfileBuiltFromTemplateToCreateASystem.json, oneview_redfish_toolkit/mockups/oneview/ServerProfileBuiltFromZoneWithoutStorageToCreateASystem.json, oneview_redfish_toolkit/mockups/redfish/CapabilitiesObject.json, oneview_redfish_toolkit/mockups/redfish/ComputerSystem.json, oneview_redfish_toolkit/mockups/redfish/PostToComposeSystem.json, oneview_redfish_toolkit/mockups/redfish/PostToComposeSystemWithoutStorage.json, oneview_redfish_toolkit/strategy_multiple_oneview.py, oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
=> Add support for Description in Composed system and Capabilities Object

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/config.py, oneview_redfish_toolkit/multiple_oneview.py, oneview_redfish_toolkit/tests/base_flask_test.py
=> Log elapsed time for request in debug mode

oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_session.py, oneview_redfish_toolkit/tests/test_client_session.py
-Fix unit tests for conf mode
-Fix client session tests
=> Fix unit tests for conf mode and client session tests

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/api/storage_resource_block.py, oneview_redfish_toolkit/api/util/power_option.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/conf/redfish.conf, oneview_redfish_toolkit/config.py, oneview_redfish_toolkit/services/computer_system_service.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
=> Power off the server on compose/decompose request

oneview_redfish_toolkit/client_session.py
- Adding lock as global variable and reusing on methods that need it
Closes #448
=> Fix threading lock

requirements.txt, test-requirements.txt
This commit freezes the dependencies in requirements.txt and test-requirements.txt to avoid problem in "production" environment with auto update of versions.
Closes #321
=> Freezes build dependencies

oneview_redfish_toolkit/blueprints/session.py, oneview_redfish_toolkit/client_session.py, oneview_redfish_toolkit/tests/blueprints/test_session.py
=> Support for Delete Session (logout)

oneview_redfish_toolkit/api/network_device_function_collection.py, oneview_redfish_toolkit/blueprints/chassis.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/mockups/redfish/NetworkDeviceFunctionCollection.json, oneview_redfish_toolkit/tests/blueprints/test_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_manager.py
=> Not found error should not return 500 on requests

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/chassis.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/resource_block.py, oneview_redfish_toolkit/blueprints/thermal.py, oneview_redfish_toolkit/category_resource.py, oneview_redfish_toolkit/multiple_oneview.py, oneview_redfish_toolkit/strategy_multiple_oneview.py, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py, oneview_redfish_toolkit/tests/blueprints/test_thermal.py, oneview_redfish_toolkit/tests/test_multiple_oneview.py
=> Cached categories for OneView resources

oneview_redfish_toolkit/api/event_service.py, oneview_redfish_toolkit/api/schemas.py, oneview_redfish_toolkit/api/service_root.py, oneview_redfish_toolkit/api/session_service.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/event_service.py, oneview_redfish_toolkit/blueprints/session_service.py, oneview_redfish_toolkit/blueprints/subscription.py, oneview_redfish_toolkit/mockups/redfish/EventDestination.json, oneview_redfish_toolkit/mockups/redfish/EventService.json, oneview_redfish_toolkit/mockups/redfish/EventServiceDisabled.json, oneview_redfish_toolkit/mockups/redfish/ServiceRoot.json, oneview_redfish_toolkit/mockups/redfish/SessionService.json, oneview_redfish_toolkit/mockups/redfish/SessionServiceDisabled.json, oneview_redfish_toolkit/mockups/redfish/Subscription.json, oneview_redfish_toolkit/schemas/SessionService.v1_1_3.json, oneview_redfish_toolkit/tests/api/test_service_root.py, oneview_redfish_toolkit/tests/api/test_session_service.py, oneview_redfish_toolkit/tests/api/test_subscription.py, oneview_redfish_toolkit/tests/blueprints/test_event_service.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py, oneview_redfish_toolkit/tests/blueprints/test_session_service.py, oneview_redfish_toolkit/tests/blueprints/test_subscription.py, oneview_redfish_toolkit/util.py
- Event Service should not be enabled in "session" mode.
- Session Service should not be enabled in "conf" mode.
Closes #438
=> Session Service and Event Service should be enabled according authentication mode

oneview_redfish_toolkit/api/server_profile_template_resource_block.py, oneview_redfish_toolkit/api/storage_resource_block.py, oneview_redfish_toolkit/mockups/redfish/SPTResourceBlockWithOnlyOneZone.json, oneview_redfish_toolkit/mockups/redfish/ServerProfileTemplateResourceBlock.json, oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json, oneview_redfish_toolkit/mockups/redfish/StorageResourceBlockComposed.json
=> Adds SharingEnabled for Network RB and SharingCapable for Storage RB

oneview_redfish_toolkit/services/computer_system_service.py, oneview_redfish_toolkit/tests/blueprints/test_zone_collection.py
- Adding filter for controller mode, checking if it is HBA or Mixed
Closes #478
=> Extend additional check for storage controller settings

scripts/oneview-redfish-toolkit
=> Package installation requirements

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/conf/logging.conf, oneview_redfish_toolkit/util.py, scripts/oneview-redfish-toolkit
=> Stop service on production environment

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/util/response_builder.py, oneview_redfish_toolkit/mockups/errors/InvalidCredentialsJsonKey.json, oneview_redfish_toolkit/mockups/errors/InvalidJsonKey.json, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_chassis.py
- Adding error_400 treatment on ResponseBuilder
- Adapting unit tests for this change
Closes #499
=> Bad request errors are not treated on ResponseBuilder

oneview_redfish_toolkit/api/thermal.py, oneview_redfish_toolkit/mockups/redfish/BladeChassisThermal.json, oneview_redfish_toolkit/mockups/redfish/EnclosureChassisThermal.json, oneview_redfish_toolkit/mockups/redfish/RackChassisThermal.json
=> It fixes the Temparature object inside Thermal object

README.md
=> Adding instruction about how to install Toolkit offline

oneview_redfish_toolkit/app.py
=> Fixes: The app does not up properly without the "certs" files path in redfish.conf

oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/zone.py
=> Adds decorator single_oneview to computer system and zone blueprints
