HewlettPackard/oneview-redfish-toolkit

oneview_redfish_toolkit/blueprints/service_root.py, oneview_redfish_toolkit/tests/blueprints/test_service_root.py
get_status() was being used instead of get_version() which actually contains the UUID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/49)
=> Fix service_root.py to use UUID from appliance node info

oneview_redfish_toolkit/blueprints/chassis.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/blueprints/manager.py, oneview_redfish_toolkit/tests/blueprints/test_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_manager.py
Fixed #160 
Adding ETag in the response header for computer system and chassis.
=> Adding ETag in the response header

tox.ini
Choosing python has lead to docs generation error when running on Windows 7 with python 3.5.
=> Unpin python executable from docs generation

CHANGELOG.md, oneview_redfish_toolkit/app.py, redfish.conf
The debug option allows the user to decide whether the Flask HTTP server must run in debug mode or not.
Closes #236
=> Add debug option into the Redfish service configuration file

CHANGELOG.md, oneview_redfish_toolkit/api/resource_block_collection.py, oneview_redfish_toolkit/blueprints/resource_block_collection.py, oneview_redfish_toolkit/mockups/redfish/ResourceBlockCollection.json, oneview_redfish_toolkit/mockups/redfish/ResourceBlockCollectionEmpty.json, oneview_redfish_toolkit/tests/api/test_resource_block_collection.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block_collection.py
This commit:
- Adds ResourceBlocks for each Server Profile Template in the ResourceBlocks Collection
- Removes the 404 error from ResourceBlocks Collection api when the collection is empty
- Increases tests to cover server profile template in the ResourceBlocks Collection api
Closes #259
=> Adds ResourceBlocks for each Server Profile Template in the ResourceBlocks Collection

CHANGELOG.md, oneview_redfish_toolkit/api/storage_resource_block.py, oneview_redfish_toolkit/blueprints/resource_block.py, oneview_redfish_toolkit/mockups/oneview/Drive.json, oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json, oneview_redfish_toolkit/tests/api/test_storage_resource_block.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
- Handles Oneview's Drive as a resource block and return a redfish object with Storage Resource Block information when you request /redfish/v1/CompositionService/ResourceBlocks/uuid-of-oneview's-drive.
- Changes and adds unit tests to blueprints/test_resource_block .py and api/test_storage_resource_block.py
PS.: Links inside redfish Storage Resource Block object are missing, it will be included in another task.
Closes #293
=> Implement Storage ResourceBlock 

oneview_redfish_toolkit/api/storage_composition_details.py, oneview_redfish_toolkit/api/storage_drive_composition_details.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/storage_composition_details.py, oneview_redfish_toolkit/conf/redfish.conf, oneview_redfish_toolkit/mockups/oneview/Drive.json, oneview_redfish_toolkit/mockups/oneview/DriveEnclosure.json, oneview_redfish_toolkit/mockups/redfish/StorageCompositionDetails.json, oneview_redfish_toolkit/mockups/redfish/StorageDriveCompositionDetails.json, oneview_redfish_toolkit/mockups/redfish/StorageResourceBlock.json, oneview_redfish_toolkit/tests/api/test_storage_composition_details.py, oneview_redfish_toolkit/tests/api/test_storage_drive_composition_details.py, oneview_redfish_toolkit/tests/blueprints/test_storage_composition_details.py, redfish.conf
Adds endpoints to Drives and Storage details of ResourceBlock
Includes:
- StorageDriveCompositionDetails to represent a redfish object of Drives of a Storage
- StorageCompositionDetails to represent a redfish object of Storage of a Storage ResourceBlock
- Endpoints to show that objects
- Unit tests to that objects and endpoints
It is related to #293
=> Storage Resource Block Details (Storage and Drives)

oneview_redfish_toolkit/api/zone.py, oneview_redfish_toolkit/blueprints/zone.py, oneview_redfish_toolkit/mockups/oneview/ServerProfileTemplate.json, oneview_redfish_toolkit/mockups/redfish/ZoneWithoutDrives.json, oneview_redfish_toolkit/tests/api/test_zone.py, oneview_redfish_toolkit/tests/blueprints/test_zone.py
- Storage Resource Blocks are available only if storage controller is configured and is not Embedded
- Adds unit tests to cover the scenario above
Ps.: This PR closes 2 issues (#309  and #299), but that issues will be put on CHANGELOG only after the Sprint to avoid merge problems.
Closes #299 
Closes #309
=> Include Storage resource blocks in a Resource Zone

oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
- The uuid used to reset was changed from server profile to server hardware fixing the error
Closes #335
=> Fixes endpoint to reset a server hardware of a System

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
Before this commit when we are trying create a
Composed System without storage and the Server Profile
related have not a local storage controller configured
properly, we receive a error.
Now, we are allowing create a Composed System without
Storage when the Server Profile Template related has not
a valid local storage controller configured.
=> Allows create properly a Composed System without Storage

CHANGELOG.md, README.md
Updating list of enhancements/fixes and new redfish resources at CHANGELOG.
Also, adding limitation about Event Service that needs to use API 500 (workaround since current implementation does not work with API 600)
=> updating CHANGELOG and README (sprint 17 - 20)

oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_create_computer_system.py
- In particular case, we are avoiding redirection to GET when we call POST redfish/v1/Systems
to create a Composed System
Closes #373
=> Avoids http redirection when access URI without slash at end

oneview_redfish_toolkit/api/server_hardware_resource_block.py, oneview_redfish_toolkit/api/status_mapping.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py
- Updating CompositionState mapping by including one more value
- Adding server profile check when a server hardware state not found in CompositionState mapping. If ServerHardware has a server profile it will be composed and if not, it will be unused
- Updating resource block unit test with this change and creating a new unit test when server hardware has not a server profile
Closes #380
=> Update CompositionState of Computer System Resource Block

.gitignore, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/conf/redfish.conf, requirements.txt, run.sh
- Changes the app.py code to use CherryPy standard;
- Adds TransLogger to handler logs between cherrypy and flask app
- Uses Daemonizer plugin of the cherrypy to run the app as a daemon process
- Changes the requirements.txt adding the cherrypy to be installed
Closes #348
=> Change Oneview Redfish Toolkit to use CherryPy

oneview_redfish_toolkit/api/blade_chassis.py, oneview_redfish_toolkit/mockups/redfish/BladeChassis.json, oneview_redfish_toolkit/tests/api/test_blade_chassis.py, oneview_redfish_toolkit/tests/blueprints/test_chassis.py
- Updates on BladeChassis checking if the server hardware has a server profile applied.
- Updates link with the ServerProfile UUID, or empty if not.
Closes #389
=> Updates Links to ComputerSytems in the Chassis resource

oneview_redfish_toolkit/api/computer_system.py, oneview_redfish_toolkit/blueprints/computer_system.py, oneview_redfish_toolkit/handler_multiple_oneview.py, oneview_redfish_toolkit/mockups/oneview/LabelForServerProfile.json, oneview_redfish_toolkit/mockups/oneview/ServerProfileWithLabels.json, oneview_redfish_toolkit/services/computer_system_service.py, oneview_redfish_toolkit/strategy_multiple_oneview.py, oneview_redfish_toolkit/tests/api/test_computer_system.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system.py
- Creating a new handle to post a new label associated with a server profile using server profile template description as label
- Replacing server profile template description from server profile to use labels associated with a server profile
- Fixing unit tests to use labels instead server profile description
Closes #370
=> Use a label to save template_UUID instead of Description attribute in the server profile

oneview_redfish_toolkit/api/errors.py, oneview_redfish_toolkit/api/schemas.py, oneview_redfish_toolkit/api/session.py, oneview_redfish_toolkit/api/session_collection.py, oneview_redfish_toolkit/app.py, oneview_redfish_toolkit/blueprints/session.py, oneview_redfish_toolkit/client_session.py, oneview_redfish_toolkit/mockups/redfish/Session.json, oneview_redfish_toolkit/mockups/redfish/SessionCollection.json, oneview_redfish_toolkit/mockups/redfish/SessionCollectionEmpty.json, oneview_redfish_toolkit/mockups/redfish/SessionForLoginWithDomain.json, oneview_redfish_toolkit/tests/api/test_session.py, oneview_redfish_toolkit/tests/base_flask_test.py, oneview_redfish_toolkit/tests/blueprints/test_session.py, oneview_redfish_toolkit/tests/test_client_session.py
- Adds SessionCollection endpoint
- Adds endpoint of Session by id
- Removes session when authorization error is raised by Oneview
- Supports more than one session in cache
Closes #407 
Closes #408
=> Login session workflow

oneview_redfish_toolkit/blueprints/zone.py, oneview_redfish_toolkit/blueprints/zone_collection.py, oneview_redfish_toolkit/services/logging_service.py, oneview_redfish_toolkit/services/zone_service.py
Closes #447 
The prefix of that new logs is `counter` and just is logged in debug level.
This is a example of result in log after the commit:
```
2018-09-18 17:12:39,859 - root - WARNING - Authentication mode set to session. SCMB events will be disabled
2018-09-18 17:12:39,860 - root - WARNING - Server is starting with a self-signed certificate.
2018-09-18 17:12:39,864 - root - WARNING - Using existing self-signed certs
2018-09-18 17:12:47,827 - root - DEBUG - AuthLoginDomain not specified on session creation
2018-09-18 17:12:49,835 - perf - DEBUG - Thread 140382398568192 OneView process: 0
2018-09-18 17:12:49,836 - perf - DEBUG - Thread 140382398568192 Redfish process: 2.008012294769287
2018-09-18 17:12:49,838 - perf - DEBUG - Thread 140382398568192 Total process: 2.008012294769287 …
```
=> Adds logs: info about how many OV and Redfish resources for Zone and Zone Collection

oneview_redfish_toolkit/multiple_oneview.py
=> Fixing debug performance logs for OneView calls with errors

oneview_redfish_toolkit/mockups/redfish/ComputerSystemCollection.json, oneview_redfish_toolkit/mockups/redfish/ServerHardwareResourceBlock.json, oneview_redfish_toolkit/mockups/redfish/ServerProfileTemplateResourceBlock.json, oneview_redfish_toolkit/mockups/redfish/ZoneCollection.json, oneview_redfish_toolkit/services/zone_service.py, oneview_redfish_toolkit/tests/api/test_computer_system_collection.py, oneview_redfish_toolkit/tests/api/test_server_hardware_resource_block.py, oneview_redfish_toolkit/tests/api/test_server_profile_template_resource_block.py, oneview_redfish_toolkit/tests/api/test_zone_collection.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py, oneview_redfish_toolkit/tests/blueprints/test_zone_collection.py
Closes partially #428 
Previously the application did **1 + N** requests to retrieve the enclosures URI with valid drive enclosures, which **N** is the number of enclosures on OneView.
Now the application just need **1** request to retrieve this data.
These requests is performed for the Resource Block GET request.
We have an average reduction of **3** OneView requests per Resource Block GET request.
Below there is a graph comparing previous and currently performance with the elapsed time to retrieve each one of all 111 Resource Blocks on the DCS that we have:
This improvement also impacts on ResourseZoneCollection and ComputerSystemCollection.
=> Performance improvement on ResourceBlock OneView data request

oneview_redfish_toolkit/handler_multiple_oneview.py, oneview_redfish_toolkit/mockups/oneview/LogicalEnclosures.json, oneview_redfish_toolkit/services/zone_service.py, oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py, oneview_redfish_toolkit/tests/blueprints/test_resource_block.py, oneview_redfish_toolkit/tests/blueprints/test_zone_collection.py
Closes partially #428
Previously the application did  **N²** requests to retrieve the enclosures URI with the same enclosureGroupURI from the ServerProfileTemplates related with the ResourceBlock.
Now the application just need **1** request to retrieve this data.
These requests is performed for the Resource Block GET request.
We have an average time from **1.70s** on previous version to **0.89s** on current version for ResourceBlock GET request.
And we have an average reduction of **6** OneView requests per Resource Block GET request.
Below there is a graph comparing previous and currently performance with the elapsed time to retrieve each one of all 111 Resource Blocks on the DCS that we have:
This improvement also impacts on ResourceZoneCollection and ComputerSystemCollection.
=> Performance improvement for Resource Block

oneview_redfish_toolkit/blueprints/resource_block.py, oneview_redfish_toolkit/multiple_oneview.py, oneview_redfish_toolkit/single_oneview_context.py, oneview_redfish_toolkit/tests/test_multiple_oneview.py, oneview_redfish_toolkit/tests/test_single_oneview_context.py
Closes #464 
Implementing Single OneView Context.
With this implementation the solution does not have to search in all OneViews after get the OneView that it's working with inside the same request context. Before this implementation every "get_all()" call to retrieve OneView data was requested on each one of multiple OneViews. With this implementation, after the application find any resource on one of multiple OneViews, all the subsequent calls will be requested only on that same OneView.
On the graph below there is the comparison before and after this implementation, for an Storage ResourceBlock request on toolkit API using three mulitple OneViews, reducing from **21** OneView requests needed to **13** requests, and elapsed time from **2.18** seconds to **0.88** seconds:
=> Improvement performance for multiple OneViews
